### ISSUE TITLE
Support other entities than players

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/wielded_light#1]
Using the technique of wielded_light on for example dropped items, mobs and vehicles would be quite useful.

**Comment by bell07** [comment]
I am unsure about further development direction for wielded_light. 
Found https://github.com/minetest/minetest/pull/6363 , already merged to development version, maybe the beter way for entities (+dropped item).
If this is done: https://github.com/minetest/minetest/issues/6921 the wielded_light gets obsolete or needs to be rewritten..
I leave this issue open as reminder

**Comment by tacotexmex** [comment]
> Found minetest/minetest#6363 , already merged to development version, maybe the beter way for entities (+dropped item).

That's very different from emitting light onto surrounding surfaces though. (doesn't scratch my throwing-torches-down-a-pit itch 🙂)

**Comment by bell07** [comment]
Played around with minetest-mods/throwing and API:

![screenshot_20180507_190239](https://user-images.githubusercontent.com/4731334/39714128-65f72aea-5229-11e8-938d-ada759e723cd.png)

![screenshot_20180507_190244](https://user-images.githubusercontent.com/4731334/39714136-68aeb1cc-5229-11e8-9f59-5bc511bbad11.png)

```
diff --git a/init.lua b/init.lua
index 05e1b6f..4a33c2b 100644
--- a/init.lua
+++ b/init.lua
@@ -91,6 +91,10 @@ local function arrow_step(self, dtime)
        local pos = self.object:getpos()
        local node = minetest.get_node(pos)
 
+       if minetest.global_exists("wielded_light") then
+               wielded_light.update_light(vector.round(pos), 14)
+       end
+
        local logging = function(message, level)
                minetest.log(level or "action", "[throwing] Arrow "..(self.item or self.name).." throwed by player "..self.player.." "..tostring(self.timer).."s ago "..message)
        end
@@ -165,7 +169,7 @@ local function arrow_step(self, dtime)
                self.object:remove()
                logging("reached ignore. Removing.")
                return
-       elseif node.name ~= "air" then
+       elseif node.name ~= "air" and node.name:sub(1,13) ~= "wielded_light" then
                if self.target ~= throwing.target_object then -- throwing.target_both, nil, throwing.target_node, or any invalid value
                        if hit(pos, node, nil) ~= false then
                                self.object:remove()


```

**Comment by tacotexmex** [comment]
That looks awesome. I'm thinking of if this could integrate with my [sling](https://github.com/minetest-mods/sling) mod so that the lighting is applied to all items that propagates light…

**Comment by bell07** [comment]
https://github.com/minetest-mods/throwing/pull/16
sling does work out of the box with enhanced throwing version ;-)

**Comment by tacotexmex** [comment]
This is brilliant, bell07. Thank you so much!
