### ISSUE TITLE
Custom Callback not Working

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/wielded_light#13]
Can you tell me what I am doing wrong?

```lua
wielded_light.register_item_light("3d_armor:helmet_diamond", 10)

wielded_light.register_player_lightstep(function(player)
	local armor_inv = minetest.get_inventory({
		type = "detached",
		name = player:get_player_name() .. "_armor",
	})

	if armor_inv then
		for k, stack in pairs(armor_inv:get_list("armor")) do
			wielded_light.track_user_entity(player, "armor", stack:get_name())
		end
	end
end)
```

With the helmet equipped in my armor inventory, it is not emitting any light. If I change `stack:get_name()` to `"3d_armor:helmet_diamond"`, it works.

**Comment by oversword** [comment]
@AntumDeluge I see the issue, to avoid anything being overwritten you should use a different category for each slot / armour type, as you are overwriting it each time you track a new one with the same category. `"armor"..tostring(k)` should work for all scenarios

**Comment by AntumDeluge** [comment]
@oversword Thank you. [Git it fixed](https://github.com/AntumMT/mod-3d_armor_light).
