### ISSUE TITLE
"get_entity_name" Deprecated

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/wielded_light#18]
```
WARNING[Server]: Deprecated call to "get_entity_name (at C:\Games\Minetest\bin\..\mods\wielded_light\init.lua:99)
```

init.lua:99:
```lua
return entity and (entity.obj:is_player() or entity.obj:get_entity_name() or false)
```

I'm not sure how it is supposed to be updated. I thought it would be `entity.obj:get_name()`, but that didn't work.

**Comment by Niklp09** [comment]
Fixed in https://github.com/minetest-mods/wielded_light/commit/1646439ac4924f534af05d639af900d1d44506cd.
