### ISSUE TITLE
Invalid vector.add crashes server.

### ISSUE THREAD

**Issue by debagos** [minetest-mods/wielded_light#21]
Today my server crashed with the following error message:
```lua
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'wielded_light' in callback environment_Step(): ...i/github/minetest-5.5.0/bin/../builtin/common/vector.lua:154: attempt to perform arithmetic on field 'x' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	...i/github/minetest-5.5.0/bin/../builtin/common/vector.lua:154: in function 'add'
ERROR[Main]: 	...ub/minetest-5.5.0/bin/../mods/mesecons/mesecons/init.lua:98: in function <...ub/minetest-5.5.0/bin/../mods/mesecons/mesecons/init.lua:93>
ERROR[Main]: 	...test-5.5.0/bin/../mods/mesecons/mesecons/actionqueue.lua:137: in function 'execute'
ERROR[Main]: 	...test-5.5.0/bin/../mods/mesecons/mesecons/actionqueue.lua:111: in function <...test-5.5.0/bin/../mods/mesecons/mesecons/actionqueue.lua:73>
ERROR[Main]: 	...i/github/minetest-5.5.0/bin/../builtin/game/register.lua:425: in function <...i/github/minetest-5.5.0/bin/../builtin/game/register.lua:409>
```
And no, I have no idea why the traceback is showing traces from the Mesecons mod...
This is not the first time it happened, but the last time is months ago, so I have absolutely no idea how to reproduce the crash.

**Comment by debagos** [comment]
Minetest version: 5.5.0 release

**Comment by appgurueu** [comment]
Pretty sure this is a mesecons issue, otherwise the stack traces would be showing `wielded_light` file paths. I've experienced issues with Minetest's "responsible mod" detection as well.

**Comment by debagos** [comment]
This is a little heavy for me, since I'm not an educated coder...
Usually you get a line where the error originates form and it's very clear what's going wrong, but this is beyond my skills. :sweat_smile: 
Hence I want to thank you for your support @appgurueu!

**Comment by debagos** [comment]
This issue can be closed, since I found out wielded_light is not the culprit here.
https://github.com/minetest-mods/mesecons/issues/609
