### ISSUE TITLE
Incompatible to the builtin_item mod

### ISSUE THREAD

**Issue by bell07** [minetest-mods/wielded_light#25]
See https://content.minetest.net/threads/4470/

> I dropped a torch and let it be for over a minute, and nothing happens. At least it emits light when I hold it.

> After some testing, I disabled Animalia, Creatura, and Builtin item. After I did this, Wielded Light works again.

> Pretty sure it was the Builtin Item mod, because both mods replace the default builtin item.

Wielded Light is basically able to work together with other builtin item enhancements. Please try to add `builtin_item` into the `optional_depends` line in `wielded_light/mod.conf` file. It should look like

```
name = wielded_light
optional_depends = default, hades_core, builtin_item

```
Then buildtin_item is loaded at the first and the wielded_light is able to enhance it in proper way.

By the way, the depends.txt file can be removed in the meantime.

**Comment by rockobonaparte** [comment]
I submitted #26 to add builtin_item. I guess if it sits there, somebody can just post a fork to contentdb (however that's done).

**Comment by rockobonaparte** [comment]
The request was merged so I guess this is ... closed? Or I suppose somebody should make sure it was released.

**Comment by Niklp09** [comment]
> By the way, the depends.txt file can be removed in the meantime.

depends.txt got removed in https://github.com/minetest-mods/wielded_light/commit/3dfc2623598e095954b0a97f6bac6da7096cdf10 too.
