### ISSUE TITLE
Wielded light doesn't work under water 

### ISSUE THREAD

**Issue by rezaqqq** [minetest-mods/wielded_light#4]
Wielded light cant shed light on anything under water . Could please fix it ?

**Comment by bell07** [comment]
Please try the [under_water_shine branch](https://github.com/minetest-mods/wielded_light/tree/under_water_shine). I implemented it, but it did not work as expected (flickers) for unknown reason. Therefore I did not merged it into master. If you have idea what is wrong, let me know.

**Comment by rezaqqq** [comment]
I'm a noob so I'm closing the issue.

**Comment by bell07** [comment]
Just download the mod from URL https://github.com/minetest-mods/wielded_light/archive/under_water_shine.zip and replace the files in minetest/mods/wielded_light folder for testing...
