### ISSUE TITLE
Assert fails since builtin item entity changed in core

### ISSUE THREAD

**Issue by style-nine** [minetest-mods/wielded_light#6]
Since b9377f2 ("Rewrite builtin item entity to use collision info", 2020-04-14), this mod gives the following error:

/builtin/game/item_entity.lua:203: assertion failed!

Probably related to:

on_step = function(self, dtime, moveresult)

**Comment by style-nine** [comment]
https://github.com/minetest/minetest/commit/b9377f26a198d0383b82c76cf6904bc1797e8187

**Comment by bell07** [comment]
@style-nine Please test if fix does work. The fix should be compatible to the current version before the change too.

**Comment by style-nine** [comment]
Looks good, here.
